import type { NextPage } from 'next';
import Head from 'next/head';
import { ThemeProps } from 'theme';

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>Movie List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>About</h1>
    </>
  );
};

export default About;
