import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import { ThemeProps } from 'theme';
import Counter from '../components/counter/Counter';

const Main = styled.main`
  grid-column: 2;
  grid-row: 2;
  min-height: ${(p: ThemeProps) =>
    `calc(100vh - ${p.theme.headerHeight} - 50px)`};
`;

const Home: NextPage = () => {
  return (
    <Main>
      <Head>
        <title>Movie List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hi</h1>

      {/* <Counter /> */}
    </Main>
  );
};

export default Home;
